apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: cache-upload
  annotations:
    tekton.dev/pipelines.minVersion: "0.56.0"
    tekton.dev/tags: "cache"
spec:
  params:
    - name: pipelineRun
      type: string
      description: The name of the PipelineRun
      default: "$(context.pipelineRun.name)"
    - name: namespace
      type: string
      description: The namespace of the PipelineRun
      default: "$(context.pipelineRun.namespace)"
    - name: openshift_console_host
      type: string
      description: The URL of the cluster
    - name: image_url
      type: string
      description: The URL of the image for the Slack message
      default: https://github.com/tektoncd.png
  env:
    - name: SLACK_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: slack-webhook-url
          key: hook_url
    - name: PIPELINERUN
      value: "$(params.pipelineRun)"
    - name: NAMESPACE
      value: "$(params.namespace)"
    - name: OPENSHIFT_CONSOLE_HOST
      value: "$(params.openshift_console_host)"
    - name: IMAGE_URL
      value: "$(params.image_url)"
  # I just need curl and bash really
  image: registry.access.redhat.com/ubi9/ubi-minimal
  script: |
    #!/usr/bin/env bash
    set -eux
    haikus=(
      "Broken dreams guide us onward, through darkness, toward brighter dawns. Shattered hopes reveal lessons hidden in the night's embrace."
      "Through shattered glass, hope dances; sun rises on shattered dreams. In the silence of failure, whispers of wisdom find their way."
      "Failure's embrace teaches wisdom, and stars find their glow again. Lost in the abyss of defeat, the soul learns to rise anew."
      "In loss, find lessons hidden; dreams still rise, hope anew. Amidst the wreckage of despair, new beginnings quietly take root."
      "Night falls heavy on dreams, yet the dawn shines through scars. In the darkness, seeds of resilience sprout, reaching for the light."
      "Shattered dreams leave wisdom's mark; hearts mend beneath night's stars. Beneath the weight of sorrow, strength emerges, unbroken and resilient."
      "Dreams may falter and fall, but hope finds its own path. In the echoes of failure, new dreams are born, stronger than before."
      "Lessons from failure shine, dreams forge through shadows of loss. In the crucible of adversity, diamonds of resilience are formed."
      "Dark nights cradle broken dreams; the dawn carries new hopes. Through the veil of despair, rays of hope break through, illuminating the path forward."
      "Through every fall, lessons linger, lifting hearts toward brighter skies. In the tapestry of failure, threads of wisdom weave a path to success."
      "Tekton flows with code, GitHub repository holds, success and failure dance."
      "Failure whispers soft, lessons learned in the shadows, success rises bright."
      "YAML scripts guide paths, debugging shines through the dark, code finds peace in relief."
      "GitHub's open arms, community of code thrives, success celebrated."
      "Code weaves through pipelines, Tekton's flowchart leads the way, towards victory's embrace."
      "In the silence of failure, code finds solace in lessons, success blooms anew."
      "GitHub's branches spread wide, code's evolution takes flight, failure fuels growth's fire."
      "Debugging's gentle touch, unravels code's mysteries, relief found in clarity."
      "Tekton's pipeline sings, orchestrating code's journey, towards success's horizon."
      "YAML's structured grace, code's instructions clear and crisp, debugging with ease."
      "GitHub's pull request filed, code's collaboration thrives, success a shared dream."
      "Code walks the tightrope, between failure and success, finding balance in the journey."
      "Tekton's orchestra, code's symphony in motion, success the grand finale."
      "In the labyrinth of code, debugging lights the path, relief found in solutions."
      "GitHub's issue tracked, code's challenges met with grace, success on the horizon."
      "Code's melody plays, Tekton's rhythm guides the flow, harmony in code."
      "Failure's gentle touch, code learns from mistakes of old, success born from ashes."
      "GitHub's pulse beats strong, code's heartbeat in every line, success in collaboration."
      "Code's journey unfolds, Tekton's map leads the way, success waits at journey's end."
      "Failure's silver thread, woven through the fabric of code, success's tapestry."
      "GitHub's beacon shines, guiding code through stormy seas, success on the horizon."
      "Code's dance in the dark, Tekton's light leads the way, success in the shadows."
      "Failure's gentle rain, nourishes code's growth within, success blooms in its wake."
      "GitHub's symphony, code's harmonious chorus, success in collaboration."
      "Code's path winds and turns, Tekton's compass points the way, success's destination."
      "Failure's silent voice, whispers secrets of growth to code, success's guiding light."
      "GitHub's steady hand, code's ship in the stormy sea, success on the horizon."
      "Code's silent journey, Tekton's guide through the unknown, success found in silence."
      "Failure's gentle touch, code's path to growth revealed, success's bright beacon."
      "GitHub's open door, welcomes code with open arms, success in community."
    )
    haikus_len=${#haikus[@]}
    random_index=$((RANDOM % haikus_len))
    haiku="${haikus[random_index]}"
    json=$(cat <<EOF
    {
    "text": "PipelineRun *$PIPELINERUN* has failed",
    "attachments": [
      {
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "See <https://${OPENSHIFT_CONSOLE_HOST}/k8s/ns/${NAMESPACE}/tekton.dev~v1~PipelineRun/${PIPELINERUN}|OpenShift Console> for more details\n\n_${haiku}_"
            },
            "accessory": {
              "type": "image",
              "image_url": "${IMAGE_URL}",
              "alt_text": "From tekton with love"
            }
          }
        ]
      }
    ]
    }
    EOF
    )
    curl -X POST -H 'Content-type: application/json' --data "${json}" $SLACK_WEBHOOK_URL
